import React, { useState } from "react";
import { Brain, ChevronDown, ShieldCheck, AlertTriangle, FlaskConical, Activity, FileStack } from "lucide-react";
import { RISK_BAND_LABELS } from "@/lib/modelBands";

const BAND_STYLES = {
  A: { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200", dot: "bg-emerald-500" },
  B: { bg: "bg-teal-50", text: "text-teal-700", border: "border-teal-200", dot: "bg-teal-500" },
  C: { bg: "bg-amber-50", text: "text-amber-700", border: "border-amber-200", dot: "bg-amber-500" },
  D: { bg: "bg-orange-50", text: "text-orange-700", border: "border-orange-200", dot: "bg-orange-500" },
  E: { bg: "bg-rose-50", text: "text-rose-700", border: "border-rose-200", dot: "bg-rose-500" },
};

export default function ModelRiskPanel({ prediction, routing }) {
  const [showMethod, setShowMethod] = useState(false);

  if (!prediction) {
    return (
      <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50/50 p-5 text-center">
        <Brain className="w-7 h-7 text-slate-300 mx-auto mb-2" />
        <p className="text-sm text-slate-500 font-medium">Credit risk model not available</p>
        <p className="text-[12px] text-slate-400 mt-1">No validated production model could be routed for this application. The decision falls back to policy + AI advisory only.</p>
      </div>
    );
  }

  const band = prediction.risk_band || "C";
  const bs = BAND_STYLES[band] || BAND_STYLES.C;
  const pd = prediction.probability_of_default;
  const score = prediction.credit_risk_score;
  const contributions = prediction.feature_contributions || [];
  const riskIncreasing = contributions.filter(c => c.direction === "positive").slice(0, 4);
  const riskReducing = contributions.filter(c => c.direction === "negative").slice(0, 4);
  const qm = prediction.model_quality_metadata || {};

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-teal-500 to-indigo-500 flex items-center justify-center">
          <Brain className="w-4 h-4 text-white" />
        </div>
        <div>
          <h3 className="text-sm font-semibold text-slate-900">CreditDecide Risk Model</h3>
          <p className="text-[11px] text-slate-400">Probability of default & risk score — generated by the model, not the bureau</p>
        </div>
        {prediction.is_mock && (
          <span className="ml-auto inline-flex items-center gap-1 text-[10px] font-semibold text-amber-700 bg-amber-100 border border-amber-200 rounded-full px-2 py-0.5">
            <FlaskConical className="w-3 h-3" /> DEMO / MOCK
          </span>
        )}
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
        <div className="rounded-lg bg-slate-50 border border-slate-200 p-3">
          <div className="text-[10px] uppercase tracking-wider text-slate-400 font-semibold">Risk score</div>
          <div className="text-lg font-semibold text-slate-900">{score != null ? score.toFixed(3) : "—"}</div>
        </div>
        <div className="rounded-lg bg-slate-50 border border-slate-200 p-3">
          <div className="text-[10px] uppercase tracking-wider text-slate-400 font-semibold">Prob. of default</div>
          <div className="text-lg font-semibold text-slate-900">{pd != null ? `${(pd * 100).toFixed(2)}%` : "—"}</div>
        </div>
        <div className={`rounded-lg border p-3 ${bs.bg} ${bs.border}`}>
          <div className="text-[10px] uppercase tracking-wider opacity-70 font-semibold">Risk band</div>
          <div className="flex items-center gap-1.5">
            <span className={`w-1.5 h-1.5 rounded-full ${bs.dot}`} />
            <span className={`text-lg font-semibold ${bs.text}`}>{band} · {RISK_BAND_LABELS[band]}</span>
          </div>
        </div>
        <div className="rounded-lg bg-slate-50 border border-slate-200 p-3">
          <div className="text-[10px] uppercase tracking-wider text-slate-400 font-semibold">Bureau score</div>
          <div className="text-lg font-semibold text-slate-900">{prediction.bureau_score ?? "—"}</div>
          <div className="text-[10px] text-slate-400">{prediction.bureau_score_source || ""}</div>
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-2 mb-4 text-[11px]">
        <span className="inline-flex items-center gap-1 text-slate-600 bg-slate-100 rounded-full px-2.5 py-1">
          <Activity className="w-3 h-3" /> {prediction.model_name} · v{prediction.model_version}
        </span>
        <span className="inline-flex items-center gap-1 text-slate-600 bg-slate-100 rounded-full px-2.5 py-1">
          <FileStack className="w-3 h-3" /> {prediction.feature_set_version}
        </span>
        {qm.role && (
          <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 ${qm.role === "champion" ? "text-teal-700 bg-teal-100" : qm.role === "benchmark" ? "text-slate-600 bg-slate-100" : "text-indigo-700 bg-indigo-100"}`}>
            <ShieldCheck className="w-3 h-3" /> {qm.role}
          </span>
        )}
      </div>

      {(riskIncreasing.length > 0 || riskReducing.length > 0) && (
        <div className="grid sm:grid-cols-2 gap-3 mb-2">
          <div className="rounded-lg border border-rose-200 bg-rose-50/40 p-3">
            <div className="text-[11px] uppercase tracking-wider text-rose-600 font-semibold mb-1.5">Top risk-increasing factors</div>
            {riskIncreasing.length === 0 && <p className="text-[12px] text-slate-400">None</p>}
            {riskIncreasing.map((c, i) => (
              <div key={i} className="flex items-center justify-between text-[12px] py-0.5">
                <span className="text-slate-700">{c.feature.replace(/_/g, " ")}</span>
                <span className="font-mono text-rose-600">+{c.contribution.toFixed(3)}</span>
              </div>
            ))}
          </div>
          <div className="rounded-lg border border-emerald-200 bg-emerald-50/40 p-3">
            <div className="text-[11px] uppercase tracking-wider text-emerald-600 font-semibold mb-1.5">Top risk-reducing factors</div>
            {riskReducing.length === 0 && <p className="text-[12px] text-slate-400">None</p>}
            {riskReducing.map((c, i) => (
              <div key={i} className="flex items-center justify-between text-[12px] py-0.5">
                <span className="text-slate-700">{c.feature.replace(/_/g, " ")}</span>
                <span className="font-mono text-emerald-600">{c.contribution.toFixed(3)}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <button
        onClick={() => setShowMethod(s => !s)}
        className="mt-3 inline-flex items-center gap-1 text-[12px] font-medium text-slate-600 hover:text-slate-900"
      >
        <ChevronDown className={`w-3.5 h-3.5 transition-transform ${showMethod ? "rotate-180" : ""}`} />
        Model & methodology
      </button>

      {showMethod && (
        <div className="mt-3 pt-3 border-t border-slate-100 space-y-3 text-[12px]">
          {routing && (
            <div>
              <div className="text-[11px] uppercase tracking-wider text-slate-400 font-semibold mb-1">Automatic model routing</div>
              <p className="text-slate-600 mb-2">{routing.selection_reason}</p>
              <div className="flex flex-wrap gap-1.5">
                {(routing.ranked_models || []).map((r) => (
                  <span key={r.model_name} className={`text-[11px] rounded-full px-2 py-0.5 ${r.model_name === routing.selected_model ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-600"}`}>
                    {r.rank}. {r.model_name} ({r.role})
                  </span>
                ))}
                {routing.fallback_chain?.length > 0 && (
                  <span className="text-[11px] text-slate-400 self-center">fallback: {routing.fallback_chain.join(" → ")}</span>
                )}
              </div>
            </div>
          )}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
            <Meta label="Model type" value={prediction.model_type} />
            <Meta label="Validation" value={qm.validation_status || "—"} />
            <Meta label="AUC" value={qm.auc?.toFixed(2) || "—"} />
            <Meta label="Gini" value={qm.gini?.toFixed(2) || "—"} />
            <Meta label="Brier" value={qm.brier?.toFixed(3) || "—"} />
            <Meta label="Feature set" value={prediction.feature_set_version} />
            <Meta label="Predicted at" value={prediction.prediction_timestamp?.slice(0, 19).replace("T", " ") || "—"} />
            <Meta label="Environment" value={prediction.environment || "—"} />
          </div>
          <p className="text-[11px] text-slate-400 flex items-start gap-1.5">
            <AlertTriangle className="w-3 h-3 mt-0.5 shrink-0" />
            The risk model produces PD & risk score only. The final lending decision is made by the authoritative policy engine. The bureau score is stored separately and is not the CreditDecide risk score.
          </p>
        </div>
      )}
    </div>
  );
}

function Meta({ label, value }) {
  return (
    <div className="rounded-lg bg-slate-50 border border-slate-200 px-2.5 py-2">
      <div className="text-[10px] uppercase tracking-wider text-slate-400 font-semibold">{label}</div>
      <div className="text-[12px] font-medium text-slate-700 truncate">{value}</div>
    </div>
  );
}