import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { genId, apiError, apiSuccess, readBody, resolveOrganization, audit, findIdempotent } from "../../shared/utils.ts";
import { getPolicy, evaluatePolicy } from "../../shared/policyEngine.ts";
import { generateUnderwritingMemo } from "../../shared/aiUnderwriter.ts";
import { finalizeDecision } from "../../shared/decisionEngine.ts";

// POST /v1/applications/{id}/underwrite — runs the full underwriting evaluation.
export default async function(req: Request): Promise<Response> {
  try {
    const base44 = createClientFromRequest(req);
    const body = await readBody(req);
    const { organization_id, actor, actor_type } = await resolveOrganization(base44);
    const { application_id, policy_id } = body;

    if (!application_id) return apiError("VALIDATION_ERROR", "application_id is required.", 400);

    const idempotencyKey = req.headers.get("idempotency-key") || body.idempotency_key;
    const existing = await findIdempotent(base44, "UnderwritingDecision", organization_id, idempotencyKey);
    if (existing) {
      const app = (await base44.asServiceRole.entities.Application.filter({ id: application_id, organization_id }, "-created_date", 1))[0];
      return apiSuccess(buildDecisionResponse(app, existing), 200);
    }

    const apps = await base44.asServiceRole.entities.Application.filter({ id: application_id, organization_id }, "-created_date", 1);
    if (apps.length === 0) return apiError("APPLICATION_NOT_FOUND", `Application ${application_id} was not found.`, 404);
    const app = apps[0];

    await base44.asServiceRole.entities.Application.update(app.id, { status: "underwriting" });

    // 1. Load risk signals (must have been generated by /analyze)
    const signals = await base44.asServiceRole.entities.RiskSignal.filter({ application_id, organization_id }, "-created_date", 200);
    const evidence = await base44.asServiceRole.entities.Evidence.filter({ application_id, organization_id }, "-created_date", 200);

    if (signals.length === 0) return apiError("ANALYSIS_REQUIRED", "Run POST /v1/applications/{id}/analyze before underwriting.", 409);

    // 2. Load borrower + profiles for the AI memo
    const borrowers = await base44.asServiceRole.entities.Borrower.filter({ id: app.borrower_id, organization_id }, "-created_date", 1);
    const creditProfiles = await base44.asServiceRole.entities.CreditProfile.filter({ application_id, organization_id }, "-created_date", 1);
    const financialProfiles = await base44.asServiceRole.entities.FinancialProfile.filter({ application_id, organization_id }, "-created_date", 1);

    // 3. Policy evaluation (lender policy — AI cannot override)
    const orgPolicies = await base44.asServiceRole.entities.Policy.filter({ organization_id, status: "active" }, "-created_date", 50);
    const policy = getPolicy(policy_id || app.policy_id || "consumer-v1", orgPolicies);
    const policyOutcome = evaluatePolicy(policy, signals);

    // 4. AI underwriting memo (references evidence only)
    const ai = await generateUnderwritingMemo(base44, {
      borrower: borrowers[0] || {},
      application: app,
      credit: creditProfiles[0] || {},
      financial: financialProfiles[0] || {},
      signals,
      evidence,
      policyOutcome
    });

    // 5. Final decision (separation enforced)
    const decision = finalizeDecision({ application: app, signals, policyOutcome, ai });

    const decisionRecord = await base44.asServiceRole.entities.UnderwritingDecision.create({
      organization_id,
      application_id,
      policy_id: policy.policy_id,
      policy_version: policy.version,
      decision: decision.decision,
      risk_score: decision.risk_score,
      probability_of_default: decision.probability_of_default,
      confidence: decision.confidence,
      human_review_required: decision.human_review_required,
      policy_outcome: policyOutcome,
      ai_summary: ai.summary,
      ai_memo: ai.memo,
      positive_signals: ai.positive_signals,
      risk_factors: ai.risk_factors,
      reasons: decision.reasons,
      idempotency_key: idempotencyKey || null
    });

    await base44.asServiceRole.entities.Application.update(app.id, {
      status: "completed",
      decision: decision.decision,
      risk_score: decision.risk_score,
      probability_of_default: decision.probability_of_default,
      confidence: decision.confidence,
      human_review_required: decision.human_review_required,
      reasons: decision.reasons
    });

    await audit(base44, organization_id, "decision.created", { application_id, actor, actor_type, endpoint: "POST /v1/applications/{id}/underwrite", details: { decision: decision.decision, risk_score: decision.risk_score } });

    return apiSuccess(buildDecisionResponse(app, decisionRecord), 200);
  } catch (e) {
    if (e.status) return apiError(e.code || "ERROR", e.message, e.status);
    return apiError("INTERNAL_ERROR", e.message, 500);
  }
}

function buildDecisionResponse(app: any, d: any): any {
  return {
    application_id: app?.application_number || app?.id,
    status: "completed",
    decision: d.decision,
    risk_score: d.risk_score,
    probability_of_default: d.probability_of_default,
    confidence: d.confidence,
    human_review_required: d.human_review_required,
    reasons: d.reasons || [],
    policy: { policy_id: d.policy_id, version: d.policy_version },
    ai_summary: d.ai_summary,
    ai_memo: d.ai_memo,
    positive_signals: d.positive_signals,
    risk_factors: d.risk_factors
  };
}