import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { apiError, apiSuccess, readBody, resolveOrganization, requireScope, audit, findIdempotent } from "../../shared/utils.ts";
import { getPolicy, evaluatePolicy } from "../../shared/policyEngine.ts";
import { generateUnderwritingMemo } from "../../shared/aiUnderwriter.ts";
import { buildRecommendation, finalizeDecision } from "../../shared/decisionEngine.ts";
import { calculateRate } from "../../shared/pricingEngine.ts";
import { generateAdverseActionNotice } from "../../shared/adverseActionNotice.ts";

// POST /v1/applications/{id}/underwrite — runs the full underwriting evaluation.
// Pipeline: AI Analysis -> Risk Signals -> Evidence -> Policy Engine -> Recommendation -> Final Decision.
// The AI recommendation never overrides lender policy; the final decision is authoritative.
export default async function(req: Request): Promise<Response> {
  try {
    const base44 = createClientFromRequest(req);
    const body = await readBody(req);
    const ctx = await resolveOrganization(base44, body);
    const { organization_id, actor, actor_type } = ctx;
    requireScope(ctx, "applications:write");
    const { application_id, policy_id, decision_source, override_reason, override } = body;
    const overrideDecision = override?.decision;
    const overrideReason = override?.reason || override_reason;
    const overrideActor = override?.decided_by;

    if (!application_id) return apiError("VALIDATION_ERROR", "application_id is required.", 400);

    const idempotencyKey = req.headers.get("idempotency-key") || body.idempotency_key;
    const existing = await findIdempotent(base44, "UnderwritingDecision", organization_id, idempotencyKey);
    if (existing) {
      const recs = await base44.asServiceRole.entities.UnderwritingRecommendation.filter({ application_id, organization_id }, "-created_date", 1);
      return apiSuccess({ recommendation: recs[0] || null, decision: existing }, 200);
    }

    const apps = await base44.asServiceRole.entities.Application.filter({ id: application_id, organization_id }, "-created_date", 1);
    if (apps.length === 0) return apiError("APPLICATION_NOT_FOUND", `Application ${application_id} was not found.`, 404);
    const app = apps[0];

    await base44.asServiceRole.entities.Application.update(app.id, { status: "underwriting" });

    // 1. Load risk signals + evidence (must have been generated by /analyze)
    const signals = await base44.asServiceRole.entities.RiskSignal.filter({ application_id, organization_id }, "-created_date", 200);
    const evidence = await base44.asServiceRole.entities.Evidence.filter({ application_id, organization_id }, "-created_date", 200);

    if (signals.length === 0) return apiError("ANALYSIS_REQUIRED", "Run POST /v1/applications/{id}/analyze before underwriting.", 409);

    // 2. Load borrower + profiles for the AI memo
    const borrowers = await base44.asServiceRole.entities.Borrower.filter({ id: app.borrower_id, organization_id }, "-created_date", 1);
    const creditProfiles = await base44.asServiceRole.entities.CreditProfile.filter({ application_id, organization_id }, "-created_date", 1);
    const financialProfiles = await base44.asServiceRole.entities.FinancialProfile.filter({ application_id, organization_id }, "-created_date", 1);

    // 3. Policy evaluation (lender policy — AI cannot override)
    const orgPolicies = await base44.asServiceRole.entities.Policy.filter({ organization_id, status: "active" }, "-created_date", 50);
    const policy = getPolicy(policy_id || app.policy_id, orgPolicies, app.market);
    const policyOutcome = evaluatePolicy(policy, signals);

    // 4. AI underwriting memo (references evidence only)
    const ai = await generateUnderwritingMemo(base44, {
      borrower: borrowers[0] || {},
      application: app,
      credit: creditProfiles[0] || {},
      financial: financialProfiles[0] || {},
      signals,
      evidence,
      policyOutcome
    });

    // 5. Build the recommendation (advisory — AI-informed, never overrides policy)
    const recommendation = buildRecommendation({ application: app, signals, policyOutcome, ai });

    const recommendationRecord = await base44.asServiceRole.entities.UnderwritingRecommendation.create({
      organization_id,
      application_id,
      recommendation: recommendation.recommendation,
      confidence: recommendation.confidence,
      risk_score: recommendation.risk_score,
      probability_of_default: recommendation.probability_of_default,
      reasons: recommendation.reasons,
      positive_signals: ai.positive_signals,
      risk_factors: ai.risk_factors,
      risk_signal_ids: signals.map(s => s.id),
      evidence_ids: evidence.map(e => e.id),
      policy_results: policyOutcome,
      ai_summary: ai.summary,
      ai_memo: ai.memo,
      human_review_required: recommendation.human_review_required,
      adverse_action_codes: recommendation.adverse_action_codes || [],
      generated_at: new Date().toISOString()
    });

    // 6. Final decision (authoritative — follows lender policy)
    const decision = finalizeDecision({
      application: app,
      policyOutcome,
      recommendation,
      actor: overrideActor || (actor_type === "api_key" ? `api_key:${actor}` : actor),
      decisionSource: overrideDecision ? (decision_source || "human_underwriter") : (decision_source || "policy_engine"),
      overrideReason,
      overrideDecision
    });

    // 6b. Generate regulator-compliant adverse-action notice (for adverse decisions).
    let adverseActionNotice: any = null;
    if (decision.decision !== "APPROVE" && decision.adverse_action_codes?.length) {
      const bureauEv = evidence.find((e: any) => e.source_type === "credit_report" && e.source_provider);
      const creditBureau = bureauEv?.source_provider || creditProfiles[0]?.provider || null;
      let lenderName = "the Lender";
      try {
        const orgs = await base44.asServiceRole.entities.Organization.filter({ id: organization_id }, "-created_date", 1);
        if (orgs[0]?.name) lenderName = orgs[0].name;
      } catch {}
      adverseActionNotice = generateAdverseActionNotice({
        decision: decision.decision,
        adverse_action_codes: decision.adverse_action_codes,
        market: app.market || "GB",
        borrower: borrowers[0] || null,
        application: app,
        lenderName,
        creditBureau,
        decisionTimestamp: new Date().toISOString()
      });
    }

    const decisionRecord = await base44.asServiceRole.entities.UnderwritingDecision.create({
      organization_id,
      application_id,
      recommendation_id: recommendationRecord.id,
      decision: decision.decision,
      decided_by: decision.decided_by,
      decision_source: decision.decision_source,
      policy_id: policy.policy_id,
      policy_version: policy.version,
      decision_timestamp: new Date().toISOString(),
      override_reason: decision.override_reason || null,
      risk_score: decision.risk_score,
      probability_of_default: decision.probability_of_default,
      confidence: decision.confidence,
      human_review_required: decision.human_review_required,
      policy_outcome: policyOutcome,
      reasons: decision.reasons,
      adverse_action_codes: decision.adverse_action_codes || [],
      adverse_action_notice: adverseActionNotice,
      idempotency_key: idempotencyKey || null
    });

    // 7. Risk-based pricing: calculate the interest rate (APR) for approved loans.
    const interestRate = calculateRate(policy.policy_id, decision.risk_score, decision.decision);

    await base44.asServiceRole.entities.Application.update(app.id, {
      status: "completed",
      decision: decision.decision,
      risk_score: decision.risk_score,
      probability_of_default: decision.probability_of_default,
      confidence: decision.confidence,
      human_review_required: decision.human_review_required,
      reasons: decision.reasons,
      interest_rate: interestRate
    });

    await audit(base44, organization_id, "decision.created", { application_id, actor, actor_type, endpoint: "POST /v1/applications/{id}/underwrite", credits: 20, details: { decision: decision.decision, decision_source: decision.decision_source, recommendation: recommendation.recommendation, risk_score: decision.risk_score, interest_rate: interestRate } });

    return apiSuccess({ recommendation: recommendationRecord, decision: decisionRecord, interest_rate: interestRate }, 200);
  } catch (e) {
    if (e.status) return apiError(e.code || "ERROR", e.message, e.status);
    return apiError("INTERNAL_ERROR", e.message, 500);
  }
}